### ISSUE TITLE
Request for clarification on the rules

### ISSUE THREAD

**Issue by Starwort** [Shoray2002/HelloWorld#2]
Is extraneous output (i.e. any output other than 'hello world') allowed or would it cause the submission to be invalidated? In more concrete terms, would /hello world/gi be a valid regex to validate the output, or should it be exactly /^hello world$/i

Thank you for your time.

**Comment by Shoray2002** [comment]
> Is extraneous output (i.e. any output other than 'hello world') allowed or would it cause the submission to be invalidated? In more concrete terms, would /hello world/gi be a valid regex to validate the output, or should it be exactly /^hello world$/i
> 
> Thank you for your time.

It should exactly be 'hello world'
